"""video unique filename, duration, video_metadata; analysis last_updated

Revision ID: ca3c2d67e943
Revises: 124da2b65f07
Create Date: 2025-05-21 00:39:54.615215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3c2d67e943'
down_revision: Union[str, None] = '124da2b65f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('videos', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('video_metadata', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'videos', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_column('videos', 'video_metadata')
    op.drop_column('videos', 'duration')
    op.drop_column('analyses', 'last_updated')
    # ### end Alembic commands ###
